version: '3.6'

services:
  custompios:
    image: guysoft/custompios:devel
    container_name: ${DISTRO_NAME}-build
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
      # - /mnt/sda1/CustomPiOS/src:/CustomPiOS
    devices:
      - /dev/loop-control
    labels:
      - com.centurylinklabs.watchtower.enable=true
    dns:
      - 8.8.8.8
      - 4.4.4.4

